/** Define ids for each page. */
export const PAGE_IDS = {
  ADD_STUFF: 'add-stuff',
  EDIT_STUFF: 'edit-stuff',
  LANDING: 'landing',
  LIST_STUFF: 'list-stuff',
  LIST_STUFF_ADMIN: 'list-stuff-admin',
  MANAGE_DATABASE: 'manage-database',
  NOT_AUTHORIZED: 'not-authorized',
  NOT_FOUND: 'not-found',
  SIGN_IN: 'sign-in',
  SIGN_OUT: 'sign-out',
  USER_PROFILE: 'userprofile',
  SIGN_UP: 'sign-up',
  FAQ: 'faq',
  CHAT: 'chat',
  ADD_NONPROFIT: 'add-nonprofit',
  EDIT_NONPROFIT: 'edit-nonprofit',
  LIST_NONPROFIT: 'list-nonprofit',
  LIST_NONPROFIT_ADMIN: 'list-nonprofit-admin',
  VIEW_NONPROFIT: 'view-nonprofit',
  VOLUNTEER_FORUM: 'volunteer-forum',
  DEVELOPMENT: 'development',
};
